### ISSUE TITLE
Database Error

### ISSUE THREAD

**Issue by vikasprogrammer** [ilscipio/scipio-erp#11]
I am getting this error while launching for the first time. 

org.ofbiz.entity.GenericEntityException: org.ofbiz.entity.GenericDataSourceException: Unable to esablish a connection with the database. (Unable to acquire a new connection from the pool) (Unable to esablish a connection with the database. (Unable to acquire a new connection from the pool))
        at org.ofbiz.entity.GenericDelegator.findList(GenericDelegator.java:1603) ~[ofbiz-entity.jar:?]
        at org.ofbiz.entity.util.EntityQuery.query(EntityQuery.java:526) ~[ofbiz-entity.jar:?]
        at org.ofbiz.entity.util.EntityQuery.queryList(EntityQuery.java:451) ~[ofbiz-entity.jar:?]
        at org.ofbiz.service.job.JobManager.reloadCrashedJobs(JobManager.java:395) [ofbiz-service.jar:?]
        at org.ofbiz.service.job.JobPoller$JobManagerPoller.run(JobPoller.java:223) [ofbiz-service.jar:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
Caused by: org.ofbiz.entity.GenericDataSourceException: Unable to esablish a connection with the database. (Unable to acquire a new connection from the pool)
        at org.ofbiz.entity.jdbc.SQLProcessor.getConnection(SQLProcessor.java:263) ~[ofbiz-entity.jar:?]
        at org.ofbiz.entity.jdbc.SQLProcessor.prepareStatement(SQLProcessor.java:366) ~[ofbiz-entity.jar:?]
        at org.ofbiz.entity.datasource.GenericDAO.selectListIteratorByCondition(GenericDAO.java:763) ~[ofbiz-entity.jar:?]
        at org.ofbiz.entity.datasource.GenericHelperDAO.findListIteratorByCondition(GenericHelperDAO.java:140) ~[ofbiz-entity.jar:?]
        at org.ofbiz.entity.GenericDelegator.find(GenericDelegator.java:1547) ~[ofbiz-entity.jar:?]
        at org.ofbiz.entity.GenericDelegator.findList(GenericDelegator.java:1583) ~[ofbiz-entity.jar:?]
        ... 5 more
Caused by: java.sql.SQLException: Unable to acquire a new connection from the pool
        at org.apache.commons.dbcp2.managed.ManagedConnection.updateTransactionStatus(ManagedConnection.java:130) ~[commons-dbcp2-2.2.0.jar:2.2.0]
        at org.apache.commons.dbcp2.managed.ManagedConnection.<init>(ManagedConnection.java:59) ~[commons-dbcp2-2.2.0.jar:2.2.0]
        at org.apache.commons.dbcp2.managed.ManagedDataSource.getConnection(ManagedDataSource.java:81) ~[commons-dbcp2-2.2.0.jar:2.2.0]
        at org.ofbiz.entity.connection.DebugManagedDataSource.getConnection(DebugManagedDataSource.java:52) ~[ofbiz-entity.jar:?]
        at org.ofbiz.entity.connection.DBCPConnectionFactory.getConnection(DBCPConnectionFactory.java:65) ~[ofbiz-entity.jar:?]
        at org.ofbiz.geronimo.GeronimoTransactionFactory.getConnection(GeronimoTransactionFactory.java:83) ~[ofbiz-geronimo.jar:?]
        at org.ofbiz.entity.jdbc.SQLProcessor.getConnection(SQLProcessor.java:260) ~[ofbiz-entity.jar:?]
        at org.ofbiz.entity.jdbc.SQLProcessor.prepareStatement(SQLProcessor.java:366) ~[ofbiz-entity.jar:?]
        at org.ofbiz.entity.datasource.GenericDAO.selectListIteratorByCondition(GenericDAO.java:763) ~[ofbiz-entity.jar:?]
        at org.ofbiz.entity.datasource.GenericHelperDAO.findListIteratorByCondition(GenericHelperDAO.java:140) ~[ofbiz-entity.jar:?]
        at org.ofbiz.entity.GenericDelegator.find(GenericDelegator.java:1547) ~[ofbiz-entity.jar:?]
        at org.ofbiz.entity.GenericDelegator.findList(GenericDelegator.java:1583) ~[ofbiz-entity.jar:?]
        ... 5 more
Caused by: java.util.NoSuchElementException: Unable to activate object
        at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:471) ~[commons-pool2-2.5.0.jar:2.5.0]
        at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:362) ~[commons-pool2-2.5.0.jar:2.5.0]
        at org.apache.commons.dbcp2.managed.ManagedConnection.updateTransactionStatus(ManagedConnection.java:127) ~[commons-dbcp2-2.2.0.jar:2.2.0]
        at org.apache.commons.dbcp2.managed.ManagedConnection.<init>(ManagedConnection.java:59) ~[commons-dbcp2-2.2.0.jar:2.2.0]
        at org.apache.commons.dbcp2.managed.ManagedDataSource.getConnection(ManagedDataSource.java:81) ~[commons-dbcp2-2.2.0.jar:2.2.0]
        at org.ofbiz.entity.connection.DebugManagedDataSource.getConnection(DebugManagedDataSource.java:52) ~[ofbiz-entity.jar:?]
        at org.ofbiz.entity.connection.DBCPConnectionFactory.getConnection(DBCPConnectionFactory.java:65) ~[ofbiz-entity.jar:?]
        at org.ofbiz.geronimo.GeronimoTransactionFactory.getConnection(GeronimoTransactionFactory.java:83) ~[ofbiz-geronimo.jar:?]
        at org.ofbiz.entity.jdbc.SQLProcessor.getConnection(SQLProcessor.java:260) ~[ofbiz-entity.jar:?]
        at org.ofbiz.entity.jdbc.SQLProcessor.prepareStatement(SQLProcessor.java:366) ~[ofbiz-entity.jar:?]
        at org.ofbiz.entity.datasource.GenericDAO.selectListIteratorByCondition(GenericDAO.java:763) ~[ofbiz-entity.jar:?]
        at org.ofbiz.entity.datasource.GenericHelperDAO.findListIteratorByCondition(GenericHelperDAO.java:140) ~[ofbiz-entity.jar:?]
        at org.ofbiz.entity.GenericDelegator.find(GenericDelegator.java:1547) ~[ofbiz-entity.jar:?]
        at org.ofbiz.entity.GenericDelegator.findList(GenericDelegator.java:1583) ~[ofbiz-entity.jar:?]
        ... 5 more
Caused by: java.sql.SQLException: A read-only user or a user in a read-only database is not permitted to disable read-only mode on a connection.
        at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source) ~[derby-10.14.2.0.jar:?]
        at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source) ~[derby-10.14.2.0.jar:?]
        at org.apache.derby.impl.jdbc.TransactionResourceImpl.wrapInSQLException(Unknown Source) ~[derby-10.14.2.0.jar:?]
        at org.apache.derby.impl.jdbc.TransactionResourceImpl.handleException(Unknown Source) ~[derby-10.14.2.0.jar:?]
        at org.apache.derby.impl.jdbc.EmbedConnection.handleException(Unknown Source) ~[derby-10.14.2.0.jar:?]
        at org.apache.derby.impl.jdbc.EmbedConnection.setReadOnly(Unknown Source) ~[derby-10.14.2.0.jar:?]
        at org.apache.commons.dbcp2.DelegatingConnection.setReadOnly(DelegatingConnection.java:561) ~[commons-dbcp2-2.2.0.jar:2.2.0]
        at org.apache.commons.dbcp2.PoolableConnectionFactory.activateObject(PoolableConnectionFactory.java:415) ~[commons-dbcp2-2.2.0.jar:2.2.0]
        at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:462) ~[commons-pool2-2.5.0.jar:2.5.0]
        at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:362) ~[commons-pool2-2.5.0.jar:2.5.0]
        at org.apache.commons.dbcp2.managed.ManagedConnection.updateTransactionStatus(ManagedConnection.java:127) ~[commons-dbcp2-2.2.0.jar:2.2.0]
        at org.apache.commons.dbcp2.managed.ManagedConnection.<init>(ManagedConnection.java:59) ~[commons-dbcp2-2.2.0.jar:2.2.0]
        at org.apache.commons.dbcp2.managed.ManagedDataSource.getConnection(ManagedDataSource.java:81) ~[commons-dbcp2-2.2.0.jar:2.2.0]
        at org.ofbiz.entity.connection.DebugManagedDataSource.getConnection(DebugManagedDataSource.java:52) ~[ofbiz-entity.jar:?]
        at org.ofbiz.entity.connection.DBCPConnectionFactory.getConnection(DBCPConnectionFactory.java:65) ~[ofbiz-entity.jar:?]
        at org.ofbiz.geronimo.GeronimoTransactionFactory.getConnection(GeronimoTransactionFactory.java:83) ~[ofbiz-geronimo.jar:?]
        at org.ofbiz.entity.jdbc.SQLProcessor.getConnection(SQLProcessor.java:260) ~[ofbiz-entity.jar:?]
        at org.ofbiz.entity.jdbc.SQLProcessor.prepareStatement(SQLProcessor.java:366) ~[ofbiz-entity.jar:?]
        at org.ofbiz.entity.datasource.GenericDAO.selectListIteratorByCondition(GenericDAO.java:763) ~[ofbiz-entity.jar:?]
        at org.ofbiz.entity.datasource.GenericHelperDAO.findListIteratorByCondition(GenericHelperDAO.java:140) ~[ofbiz-entity.jar:?]
        at org.ofbiz.entity.GenericDelegator.find(GenericDelegator.java:1547) ~[ofbiz-entity.jar:?]
        at org.ofbiz.entity.GenericDelegator.findList(GenericDelegator.java:1583) ~[ofbiz-entity.jar:?]
        ... 5 more

**Comment by minifreak** [comment]
Hi Vikas,

Can you provide more details about how are you trying to connect to the database? Are you using Derby or any other RDBMS?

In case you haven't, I'd recommend to take a look at our [setup guide](https://www.scipioerp.com/community/developer/installation-configuration/configuration/).

**Comment by madppiper** [comment]
Hi Vikas,

and welcome to the community. Can you check this thread: https://forum.scipioerp.com/t/cant-start-scipio/34/10 

I think your error is exactly the same. 

Thanks & regards,
Paul

**Comment by vikasprogrammer** [comment]
Thanks for quick response guys. I think it was a localized error, someone messed up the db config in my VM (its a shared VM). I simply redownloaded the repo based on @minifreak's comment and voila.. it works!
